### ISSUE TITLE
Job (scheduled task) design & tracking

### ISSUE THREAD

**Issue by bvtujo** [aws/copilot-cli#1131]
Related #1128

Scheduled tasks (jobs) run periodically in an environment are a top customer ask for Copilot. We're currently working on building out this functionality and will be tracking our ongoing work on this issue. 

## Scope of Work
Customers should be able to create a new job via a similar workflow to that used in `copilot svc init`. To make this happen, we will implement the following four commands:
```sh
copilot job init
copilot job deploy
copilot job package
copilot job status
copilot job show
copilot job delete
```

The workflow will allow customers to specify the following parameters for their jobs: 
* schedule (using either `rate` or `cron` syntax, with support for predefined schedules as described in [Rob Figueiredo's `cron` library](https://godoc.org/github.com/robfig/cron#hdr-Predefined_schedules)).
* retries (number of times to re-submit the Fargate task on a failure)
* timeout (overall time including all retries after which to stop execution)

The job will always be wrapped in a simple [state machine](https://docs.aws.amazon.com/step-functions/latest/dg/concepts-amazon-states-language.html) for error tracing purposes. The state machine will also handle the added logic required for the `--timeout` and `--retries` flags. 

### Examples
```sh
# Deploy a simple job with no retry logic. 
$ copilot job init --name reaper --schedule @hourly
$ copilot job deploy --name reaper

# Deploy a job with retries and an overall timeout period which runs at 5:00am daily.
$ copilot job init --name report-generator --schedule "0 5 * * * *" --retries 5 --timeout 3h
$ copilot job deploy --name report-generator
```

## Roadmap & Tracker

- [x] Write manifest template (#1320)
- [x] Write cloudformation template proof of concept (#1320)
- [x] Enable template execution for CF and manifests
- [x] Stub out new commands (#1335, #1351, #1352)
- [x] `job init` complete
- [x] `job deploy` complete
- [x] `job package` complete
- [x] `job delete` complete
- [ ] `job show` complete
- [ ] `job status` complete
- [x] Add "Scheduled Job" option to `init`
- [x] Add "Scheduled Job" option to `deploy`
- [x] Update buildspec template for pipelines
- [x] End to end tests

**Comment by kohidave** [comment]
I will throw in that this needs to be easier and better than using CodeBuild 😁

**Comment by mwarkentin** [comment]
@bvtujo are there still pieces outstanding or has most of this been resolved in the release of [copilot#0.5](https://github.com/aws/copilot-cli/releases/tag/v0.5.0)?

**Comment by bvtujo** [comment]
@mwarkentin Most of this is resolved in v0.5.0, with a few bugfixes and enhancements coming up in our next release. We're going to follow shortly with `job status`, `job show`, and `job logs`, but for now, Scheduled Jobs are totally deployable with Copilot!

**Comment by efekarakus** [comment]
We shipped the `job` cmd family for further `job` commands we'll create separate issues.
