### ISSUE TITLE
Enable additional sources for Copilot pipelines

### ISSUE THREAD

**Issue by efekarakus** [aws/copilot-cli#1339]
At the moment, Copilot pipelines only support a GitHub repository as a source. This issue tracks all other provider requests to for CodePipeline source integrations:

* [x] CodeCommit: https://github.com/aws/copilot-cli/issues/781
* [x] Self-hosted GitHub enterprise instance: https://github.com/aws/copilot-cli/issues/1247
* [x] Bitbucket: https://github.com/aws/copilot-cli/issues/1274
* [ ] GitLab: https://github.com/aws/copilot-cli/issues/1338

**Comment by huanjani** [comment]
## Milestones

1. **Add CodeCommit**
- [x] pipeline and repo in same account and same region
- [x] UX: auto-detect repo sources and repos
- [ ] cross-region, if possible
- [ ] cross-account, if possible

2. **Add CodeStar Connections**
- [x] connection-creation functionality
- [x] Bitbucket
- [x] GitHub version 2 source action
- [x] GitHub Enterprise
