### ISSUE TITLE
Auto Scaling Milestone I

### ISSUE THREAD

**Issue by iamhopaul123** [aws/copilot-cli#1349]
## Description
First milestone for #1154. Including Simple target tracking (without step scaling for SQS queue).

## Schedule
- [x] Update manifest
- [x] Update CFN template
- [x] Custom resource lambda function that overrides desired count to autoscaling count during deployments
- [x] Allow `svc status` to show alarms created by auto scaling
