### ISSUE TITLE
Support environment variable files in manifests

### ISSUE THREAD

**Issue by efekarakus** [aws/copilot-cli#1366]
### Ask
Enable passing multiple environment variables using external files.
```yaml
variables:
  LOG_LEVEL: info

env_file:
- <path from root of workspace>
```

See: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/taskdef-envfiles.html

From a customer ask:
> Env files are nice because they're pretty flexible/standardized -- whether you're writing a non-Docker service or a Dockerized service, you can (generally) take the same env files and re-use it across your architecture. So feels like it would really help to round-out the integration story there = )

**Comment by iamhopaul123** [comment]
## Design Proposal
```yaml
variables:
  LOG_LEVEL: info

# env file within workload workspace (same level as the workload manifest), must be suffixed with ".env"
env_file: foo.env
```
## Implementation Plan

- [x] update svc/job deploy and CFN template
- [x] update pipeline buildspec
- [x] update manifest pkg and add manifest validation (this will enable the feature)
- [ ] add to e2e test and Copilot docs

**Comment by efekarakus** [comment]
Hi folks! In the design proposal above from @iamhopaul123 he is reducing the API to a single file:
```yaml
env_file: <path>
```
The above manifest should work with environment overrides:
```
env_file: <test path>
environment:
  prod:
    env_file: <prod path>
```

Would that be sufficient for your use cases? Or do you need multiple file support? if so why?

**Comment by Lou1415926** [comment]
This is now released 🎉 in v1.14.0 https://github.com/aws/copilot-cli/releases/tag/v1.14.0 !
