### ISSUE TITLE
proposal: "env upgrade" command

### ISSUE THREAD

**Issue by efekarakus** [aws/copilot-cli#1387]
### Overview
We're proposing to introduce a new command,`env upgrade`, to upgrade the CFN template of an environment stack.

Currently the template for an environment is static so we do not have a way of adding or modifying existing resources. This command will enable us to support new shared resources, like NLBs, or change our existing template so that ALBs become optional. Copilot users shouldn't have to run this command themselves, and instead service deployments will first trigger an environment upgrade to make sure all the latest features in a manifest can be supported by the environment.

This is a prerequisite for https://github.com/aws/copilot-cli/issues/1304.  

_This command can also be the entry point in the future to apply a manifest file to an environment and override existing values in the environment stack._

### Help menu
We'll first start by supporting only the `--name`, `--app`, and `--all` flags.

```
$ copilot env upgrade -h
Upgrades the template of an environment to a new version.

Usage
  copilot env upgrade [flags]

Flags
  --name     string    Name of the environment.
  --app      string    Name of the application.
  --all      bool      Optional. Upgrade all the environments in your application.
  --diff     bool    Optional. Prints the changes that will be applied to the environment.
  --version  string    Optional. Upgrade the environment to a specific version.
  --manifest string    Optional. Path to an environment manifest file to override environment values.
```

### Wizard 🧙‍♂️

```
$ copilot env upgrade
Which environment would you like to upgrade?
> All of them
> test
> prod

⠦ Upgrade environment "test" to v0.4.0 from v0.3.0 
- Add resource NetworkLoadBalancer
```

### Milestones
- [x] Add new `cf-v1.0.0.yaml` template under `templates/environment/versions` (https://github.com/aws/copilot-cli/pull/1388)
- [x] Move legacy template under `templates/environment/versions` (https://github.com/aws/copilot-cli/pull/1388)
- [x] Update `template/env.go` to read an environment template from a specific version. (https://github.com/aws/copilot-cli/pull/1389)
  - [x] Update `template.EnvOpts` to accept a version and `ALBWorkloads`.
- [x] Add `ALBWorkloads` and `Version` options to `deploy.CreateEnvironmentInput` and update `stack/env.go`.
- [x] Update `DeployEnvironment` in the deploy pkg to handle updates and wait until the stack is available to update if busy.
- [x] Add `Version` method to `EnvDescriber` in the `describe` pkg to retrieve the version of an environment from the cloudformation template.
- [x] Implement `env upgrade` command
  -  [x] Validate
  - [x] Ask
  -  [x] Execute
