### ISSUE TITLE
Job Init Command

### ISSUE THREAD

**Issue by bvtujo** [aws/copilot-cli#1425]
This issue is to track the status of the Job Init command and related subtasks. Related #1131 

- [x] Job Init Ask (#1390) 
- [x] Job Init Validate (#1367)
- [x] Job Init Execute (#1423)

**Comment by bvtujo** [comment]
Related #1131
