### ISSUE TITLE
Support launching tasks in private subnets

### ISSUE THREAD

**Issue by efekarakus** [aws/copilot-cli#1959]
This issue is a design proposal for launching tasks in private subnets with Copilot. 

## Proposal
To support additional task placements, we’re proposing to create a new top-level field in our manifests:
```yaml
network:
  vpc:
     placement: 'public|private|isolated' # Defaults to 'public'.
     security_groups: ['id', ...]         # Defaults to empty [].
```
The `placement` field dictates in which subnets the tasks will be launched and which environment resources need to be created.
* `'public'` is our current behavior. Traffic from the internet is blocked but tasks can make external requests.
* `'private'` will launch tasks in private subnets and will create NAT Gateways for each AZ in the environment. 
* `'isolated'` will launch tasks in private subnets and will create VPC Endpoints so that communication never leaves the amazon network.

Customers that import a VPC will need to add an additional security group to their ECS tasks [to allow traffic destined for the AWS service to leave the task](https://docs.aws.amazon.com/vpc/latest/userguide/vpce-gateway.html#vpc-endpoints-security). Therefore, we’re exposing an additional field `security_groups` for customers with imported VPCs to add additional networking rules to their tasks. (#1453)

#### Load Balanced Web Service
We define a Load Balanced Web Service to be an internet-facing service. Therefore, customers will have only two `placement` options: `'public'|'private'`.  There is no `'isolated'`  option since that would mean that the load balancer is not internet-facing anymore.

#### Backend Service
A Backend Service is a service that can only be accessed within the VPC. Therefore, all `placement` options are valid: `'public'|'private'|'isolated'`.

##### Copilot VPCs
For users that deployed Backend Services in `'isolated'` subnets, we’ll make it simple to integrate with AWS services by automatically creating VPC endpoints for the following services: 

* `s3`, `ecr.dkr`, and `ecr.api` endpoints to pull the container image from ECR.
*  `logs` endpoint to write logs to CloudWatch.
*  `ssm` and `secretsmanager` endpoints to inject secrets.

Optionally, we’ll enable the following VPC endpoints if we detect a need for them in their manifest file or addons template: `autoscaling`, `elasticfilesystem`, `ssmmessages`, `dynamodb`.

##### Imported VPCs
We make it flexible to define any networking resource such as additional VPC endpoints by importing an existing VPC. In this scenario, we don’t create any additional networking resource and the users can create the necessary infrastructure.

### Use cases

1. As a user with an _imported VPC_, 
I want to deploy workloads in private subnets such that they have _no access_ to the public internet,  
so that I meet my security compliance requirements.
2. As a user with a Copilot VPC,   
I want to place my tasks in private subnets such that they have _no access_ to the public internet,
so that I meet my security compliance requirements. 
3. As a user with a Copilot VPC,   
I want to deploy workloads in private subnets such that all traffic to the internet from my tasks come out of a single IP address,
so that I can meet security compliance requirements. (#1914)
4. As a user with a Copilot VPC,   
I want to have NAT Gateways in my AZs,
so that addons deployed in private subnets can communicate to the internet (#1889)
5. As a user with an imported VPC and an existing security certificate,  
I want to connect to my service using a domain name and HTTPS,  
to meet internal compliance requirements and reach my service.

### Milestones
- [x] **Launch private tasks in imported VPCs** (https://github.com/aws/copilot-cli/pull/1979)
  - [x]  Deliver `network` with only `placement:'private'` as option for imported VPCs
- [x] **Support NAT Gateways for Copilot managed environments** (#2111, #2141)
  - [x] Add conditional resources to env template
  - [x] Pass parameter to EnvController action iff the VPC is not imported
- [x] **Support Isolated workloads for Copilot managed environments**
  - [ ] Add conditional resources to env template
  - [ ] Pass parameter to EnvController action iff the VPC is not imported
  - [ ] Parse addons and manifest template to enable additional VPC endpoints

**Comment by IsaacTrevino** [comment]
+1, This may be why my task is unable to run on private subnet. I'm using a `wget` command in my docker file (for a CloudWatch agent), which then I receive a timeout error on ECS saying failed to pull image waiting for headers.

**Comment by efekarakus** [comment]
:+1: yup, I think milestone two `"Support NAT Gateways for Copilot managed environments"` should unblock you when it becomes available!

**Comment by efekarakus** [comment]
Milestone 2: "Support NAT Gateways for Copilot managed environments" is now released in https://github.com/aws/copilot-cli/releases/tag/v1.5.0! 🚀 
When you specify in a manifest:
```yaml
network:
  vpc:
    placement: 'private'
```
and your environment is generated with Copilot, we will create NAT Gateways your AZs!

**Comment by huanjani** [comment]
For `isolated` network placement, see https://github.com/aws/copilot-cli/discussions/2378.

**Comment by mikelhamer** [comment]
I'm back at the drawing board trying to figure out if Copilot will be capable of supporting an internal enterprise application that is only accessible from an internal network. We have Direct Connect set up so anything in a private subnet can be accessed from on prem devices. We also need to be using https. Would this proposed feature fit this use case?

**Comment by huanjani** [comment]
Hello again, @mikelhamer! 

Tell us more about your use case: would an internal ALB option from Copilot do the trick? Is there anything else we should consider that would enable what you need to do?

In the meantime, what if you were to limit the IP addresses that can access the LB? 

Thanks!
