### ISSUE TITLE
Should error out if the manifest file is malformed

### ISSUE THREAD

**Issue by iamhopaul123** [aws/copilot-cli#2077]
Right now even if the manifest is malformed, for example, some incorrect indentations, we won't error out. This could be very a pain because users are not aware that their settings will not be rendered. We should probably error out earlier before CFN deployment.

**Comment by iamhopaul123** [comment]
## Implementation Plan

- [ ] Add manifest validation and consolidate existing validations elsewhere (e.g., `template` pkg) into the new manifest validation.
- [ ] Add appropriate CI to make sure the comprehensiveness for our manifest validation.
- [ ] Update the doc with the latest manifest validation for each field.

**Comment by Lou1415926** [comment]
Closed via #2881
