### ISSUE TITLE
[Design] Manifest Validation

### ISSUE THREAD

**Issue by iamhopaul123** [aws/copilot-cli#2818]
## Background

Right now even if the manifest is malformed, for example, some incorrect indentations (#2618) (https://github.com/aws/copilot-cli/issues/2618), we won't error out. Or they may remove required fields in the manifest without adding them back (#2689 (https://github.com/aws/copilot-cli/issues/2689)).

From users' perspective, this could be a pain because users might not be aware of the fact that their settings will not be rendered or rendered incorrectly. Whereas from Copilot developers' perspective, it is also paper cut for us because without having a comprehensive manifest validation means we need to constantly check the validity whenever we use their values.

## Implementation Plan

- [x] Add manifest validation
- [x] Consolidate existing validations elsewhere (e.g., `template` pkg) into the new manifest validation.
- [x] Add appropriate CI to make sure the comprehensiveness for our manifest validation.
- [x] Update the doc with the latest manifest validation for each field.
