### ISSUE TITLE
[Proposal] Customizable addons parameters

### ISSUE THREAD

**Issue by efekarakus** [aws/copilot-cli#2968]
## Problem

Today, [`addons/` templates](https://aws.github.io/copilot-cli/docs/developing/additional-aws-resources/) only accept the following 3 parameters:
```yaml
Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.
  Name:
    Type: String
    Description: The name of the service, job, or workflow being deployed.
```
These parameters are sufficient to import resources from the environment stack ([example](https://github.com/aws/copilot-cli/blob/6326103e845e555d953e08c9a8a3a6d1fa8c651a/internal/pkg/template/templates/addons/aurora/cf.yml#L56-L57)).  
However, some addons resources require information from the service stack to be able to create them. Some sample usecases are:
*  Defining an `AWS::ApiGatewayV2::Api` addon template requires the [`DiscoveryService`](https://github.com/aws/copilot-cli/blob/6326103e845e555d953e08c9a8a3a6d1fa8c651a/internal/pkg/template/templates/workloads/partials/cf/servicediscovery.yml#L1) resource's ARN.
* Defining an addon template for dashboards, metrics and alarms require the [`Service`](https://github.com/aws/copilot-cli/blob/6326103e845e555d953e08c9a8a3a6d1fa8c651a/internal/pkg/template/templates/workloads/services/lb-web/cf.yml#L118) name.
* Connecting the [`EventsQueue`](https://github.com/aws/copilot-cli/blob/6326103e845e555d953e08c9a8a3a6d1fa8c651a/internal/pkg/template/templates/workloads/partials/cf/subscribe.yml#L61) of a Worker Service to an EventBus event rule requires the QueueURL.

This design issue proposes a new mechanism to add additional parameters to the addons template.

### Parameters file
We are proposing adding a reserved file: `addons.parameters.yml` to specify values for addons stack parameters:

```
.
└── addons/
    ├── template.yml
    └── addons.parameters.yml # 🆕 reserved file.
```
Where users can provide parameter values from the parent stack:

```yaml
Parameters:
  EventsQueue: !Ref EventsQueue
  DiscoveryServiceArn: !GetAtt DiscoveryService.Arn
```

When we detect an `addons.parameters.yml` file, we augment the parameters passed in the service stack with the values the user provides. 
The values for App, Env, and Name are still passed dynamically from the CLI.

**Comment by efekarakus** [comment]
## Programming Model

- [x] (#2978) Update `filterYAMLFiles` to `filterTemplateFiles` and ignore `addons.parameters.{yml,yaml}`
   https://github.com/aws/copilot-cli/blob/8402e67710d83fb2440936bcd1cf8e794d704368/internal/pkg/addon/addons.go#L89

- [x] (#2978) Add new method with the following signature to read the contents of the `addons.parameters.yml` file:
   ```go
   // Parameters returns the content of user-defined additional CloudFormation Parameters 
   // to pass from the parent stack to Template.
   // If there is no parameters file defined, then returns "" and nil for error.
   // If the addons parameters use the reserved parameter names, then returns "" and ErrReservedParameter for error.
   func (a *Addons) Parameters() (string, error) 
   ```
   Sample prototype: https://play.golang.org/p/8pHBJJKTX1j

- [x] (#2983) Update [`template.WorkloadOpts`](https://github.com/aws/copilot-cli/blob/512987a3dddbd4de53568ee36fb02fd692473379/internal/pkg/template/workload.go#L352) to take optional AddonParameters field:
   ```go
   type WorkloadOpts struct {
      // ... existing fields
      AddonsParameters string
   }
   ```

- [x] (#2983) Update [`addons`](https://github.com/aws/copilot-cli/blob/2f9624553b7e487139531a5fa80a0b022ebdf042/internal/pkg/template/templates/workloads/partials/cf/addons.yml#L1) partials to include the parameters:
   ```yaml
     Properties:
       Parameters:
         App: !Ref AppName
         Env: !Ref EnvName
         Name: !Ref WorkloadName
         {{- if ne .AddonsParameters "" }}
         {{  .AddonsParameters | indent 8 }}
         {{- end }}
      TemplateURL:
         !Ref AddonsTemplateURL
   ```

- [x] (#2990) Update `Template()` methods in `cloudformation/stack` pkg to invoke `addons.Parameters()` and pass it down to the template.

**Comment by efekarakus** [comment]
This is now released 🎉 in v1.13.0 https://github.com/aws/copilot-cli/releases/tag/v1.13.0 !
