### ISSUE TITLE
[Design] Enable Multiple Pipelines

### ISSUE THREAD

**Issue by huanjani** [aws/copilot-cli#3231]
## Background
Though we have a [workaround](https://github.com/aws/copilot-cli/discussions/1925) for enabling multiple Copilot pipelines, we need a more built-in solution. Currently, pipeline names are auto-assigned using the "pipeline-[appName]-[repoName]" format. By changing the pipeline names in the pipeline manifest (`pipeline.yml`) before deployment (as suggested in the workaround), multiple pipelines can be created. For users following the branch-based development model, however, having different pipelines follow different branches becomes problematic when it comes time to merge the branches-- the generically-named pipeline files attempt to merge, but the user wants them to remain distinct for the separate pipelines.
Related: #1921

## Proposal
By allowing users to name their pipelines, we will avoid namespace collisions for pipelines within the same app and following the same repository. Pipeline files (`pipeline.yml` and `buildspec.yml`) will be housed within a `pipelines` subdirectory.
```
SRC_DIR
|---copilot
    |---svcA
        |---manifest.yml
    |---svcB
        |---manifest.yml
    |---pipeline.yml (pre-existing pipeline)
    |---buildspec.yml (pre-existing buildspec)
    |---pipelines
        |---dev
            |---manifest.yml
            |---buildspec.yml
        |---main
            |---manifest.yml
            |---buildspec.yml
        |---prod
            |---manifest.yml
            |---buildspec.yml
```
## Implementation Plan (Draft)
- [x] add pipeline selector to `pipeline deploy`, `pipeline status`, `pipeline show` https://github.com/aws/copilot-cli/pull/3382
- [x] add pipelines subdirectory and pathway to store pipeline manifests and buildspecs
- [x] change pipeline manifest and buildspec naming conventions https://github.com/aws/copilot-cli/pull/3381
- [x] prompt for pipeline name in `pipeline init`; handle existing pipeline name https://github.com/aws/copilot-cli/pull/3381
- [x] look for pipeline files in legacy location and new location #3267
- [x] e2e/integ tests
- [x] docs
- [x] opt: add `--local` flag to `pipeline ls`
- [ ] opt: enable workload selection (beyond selectively committing workload subdirectories)

**Comment by wstewarttennes** [comment]
@huanjani do you have an ETA for when this will be live?

**Comment by huanjani** [comment]
@wstewarttennes-- thank you for your patience! We are shooting to do another release the week of April 4. This feature should be included in that release!

**Comment by wstewarttennes** [comment]
@huanjani thanks, I appreciate the update:)

**Comment by efekarakus** [comment]
Hi folks! This feature is now released in v1.16 https://github.com/aws/copilot-cli/releases/tag/v1.16.0 🥳 
See announcement: https://aws.github.io/copilot-cli/blogs/release-v116/#create-multiple-pipelines-per-branch
Documentation: https://aws.github.io/copilot-cli/docs/concepts/pipelines/
