### ISSUE TITLE
Supporting additional AWS resources

### ISSUE THREAD

**Issue by efekarakus** [aws/copilot-cli#644]
### Overview
Currently users can’t add other resources, such as a S3 bucket, to their application’s architecture beyond what is provided in the manifest. This issue describes the proposed solution and tracks the sub-tasks to deliver the feature.

### Proposed design
We're proposing to add new top-level commands for resource categories that are likely to be common: `secrets`, `storage`, and `mesh`.

![addons](https://user-images.githubusercontent.com/879348/74207181-59b07100-4c33-11ea-9897-246776b4f740.png)

A user that runs `ecs-preview storage init` will be greeted with a helpful interactive prompt to guide them through the AWS service's concepts and fill any required fields.

The resulting directory structure will be as follows, with the generated CloudFormation resources under the `addons/` directory:
```
./
├── Dockerfile
├── LICENSE
├── app.js
└── ecs-project/
    └── {appName}/
        ├── addons/
        │   ├── {resourceName}-table.yml
        │   ├── outputs.yml
        │   ├── params.yml
        │   └── policy.yml
        └── manifest.yml
```
Users can then modify any of the files under `addons/` except `params.yml` to tweak their service. If a service is not offered as a command, they'll be able to create the CFN template themselves and drop it under `addons/`.

Output values in `outputs.yml` will be added as environment variables to their app container in their ECS service.

The templates under `addons/` will be glued together and ingested as a nested stack under their application stack.

### Milestones
1. Deliver custom addons
- [x] https://github.com/aws/amazon-ecs-cli-v2/issues/645
- [x] https://github.com/aws/amazon-ecs-cli-v2/issues/646
- [x] https://github.com/aws/amazon-ecs-cli-v2/issues/647
- [x] https://github.com/aws/amazon-ecs-cli-v2/issues/681
- [x] https://github.com/aws/amazon-ecs-cli-v2/issues/648
- [x] https://github.com/aws/amazon-ecs-cli-v2/issues/649
- [x] https://github.com/aws/amazon-ecs-cli-v2/issues/698
- [x] https://github.com/aws/amazon-ecs-cli-v2/issues/650

The remaining milestones are to create the commands that write to the `addons/` directory. 
The commands that we're considering: 
1. `ecs-preview storage init` will allow you to create S3 buckets, DDB tables, Aurora serverless db cluster.
2. `ecs-preview secrets init` will allow you to create SecretsManager secrets.
3. `ecs-preview mesh init` will allow you to create an AppMesh mesh.

**Comment by efekarakus** [comment]
@hencrice 's suggestion: for the `params.yml` file we create it with a file permission of 400 so that only the user has permission to read and hints that the file should not be modified.

**Comment by efekarakus** [comment]
Closing this issue as we delivered this feature :)
